# Generated by Django 5.2.1 on 2026-02-23 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_alter_product_image1_alter_product_image2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mpesa_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Customer's M-Pesa phone number (254XXXXXXXXX)", max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('account_reference', models.CharField(help_text='Order number shown to customer (e.g., ORD-1234)', max_length=12)),
                ('transaction_desc', models.CharField(default='Order Payment', help_text='Transaction description', max_length=200)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa confirmation code (e.g., QGK123ABC4)', max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to='application.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Payment',
                'verbose_name_plural': 'M-Pesa Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mpesa_mpesa_created_afdb88_idx'), models.Index(fields=['status'], name='mpesa_mpesa_status_4748e8_idx'), models.Index(fields=['phone_number'], name='mpesa_mpesa_phone_n_64cc83_idx'), models.Index(fields=['mpesa_receipt_number'], name='mpesa_mpesa_mpesa_r_8875ab_idx'), models.Index(fields=['order'], name='mpesa_mpesa_order_i_40c8ef_idx')],
            },
        ),
    ]
