# Generated by Django 4.2.23 on 2025-11-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_number',
            new_name='phone_number',
        ),
    ]
