# Generated by Django 5.2.1 on 2025-11-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_category_cart_order_payment_product_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
