"""
Django settings for Techhub project.
Generated by 'django-admin startproject' using Django 4.2.23.
"""

import os
from pathlib import Path
import dj_database_url

# =======================================
# BASE DIR
# =======================================
BASE_DIR = Path(__file__).resolve().parent.parent


# =======================================
# SECURITY SETTINGS
# =======================================
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-in-prod')

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = ['*', 'techhubpage.onrender.com']


# =======================================
# APPLICATIONS
# =======================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your app
    'application',

    # Cloudinary apps
    'cloudinary',
    'cloudinary_storage',
]


# =======================================
# MIDDLEWARE
# =======================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static handling for Render and local
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =======================================
# URLS + WSGI
# =======================================
ROOT_URLCONF = 'Techhub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Techhub.wsgi.application'


# =======================================
# DATABASE CONFIG
# =======================================
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:fancyMe@127.0.0.1:5432/postgres',
        conn_max_age=600
    )
}


# =======================================
# PASSWORD VALIDATION
# =======================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =======================================
# INTERNATIONALIZATION
# =======================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =======================================
# STATIC FILES
# =======================================
STATIC_URL = '/static/'

# Where collectstatic will place files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# For local static directory
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Whitenoise handles static in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# =======================================
# MEDIA FILES
# =======================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# =======================================
# CLOUDINARY SETTINGS
# =======================================
# Must be added in Vercel / Render dashboard:
# CLOUDINARY_URL = cloudinary://API_KEY:API_SECRET@CLOUD_NAME

CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL")

# Store uploaded images in Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Optional: If you want static files on Cloudinary, uncomment:
# STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'


# =======================================
# AUTH SETTINGS
# =======================================
LOGIN_URL = 'login'


# =======================================
# AUTO FIELD
# =======================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
